apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: privileged-scc
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowedCapabilities:
  - '*'
allowedFlexVolumes:
  - driver: '*'
allowedUnsafeSysctls:
  - '*'
defaultAddCapabilities:
  - '*'
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 65535
seLinuxContext:
  type: RunAsAny
runAsUser:
  type: RunAsAny
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 65535
